## 파이썬 정리

In [2]:
#test
import torch

In [53]:
a = torch.arange(3).expand(2,3)

In [54]:
b = torch.arange(2).expand(2,2)

In [55]:
a

tensor([[0, 1, 2],
        [0, 1, 2]])

In [56]:
b

tensor([[0, 1],
        [0, 1]])

In [58]:
a * b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [48]:
a + b

tensor([[0.3162, 1.3673],
        [0.0820, 1.0763]])

In [49]:
a.mul(b)

tensor([[0.0000, 0.3673],
        [0.0000, 0.0763]])

In [57]:
b @ a

tensor([[0, 1, 2],
        [0, 1, 2]])

In [60]:
b.mm(a)

tensor([[0, 1, 2],
        [0, 1, 2]])