In [9]:
import torch

a = torch.zeros(4,2)

b = a.view(2,4)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [2]:
import torch

a = torch.zeros(4,2)

b = a.view(2,4)

a.fill_(1)

a = torch.zeros(4,2)

c = a.t().reshape(8)

a.fill_(1)



tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
c

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
a = torch.zeros(4,2)

c = a.t().reshape(8)
c

NameError: name 'torch' is not defined

In [12]:
import torch
from torch import nn
from torch import Tensor

In [15]:
x = torch.randn(5,7)

In [16]:
x

tensor([[-0.3486,  0.6381, -1.4223,  1.2553,  0.7893,  0.3884, -0.7588],
        [-0.4411,  0.9279, -1.6469, -0.4797, -0.9517,  1.9363, -0.1965],
        [-1.1145,  0.0318, -1.0148, -0.4163, -0.0531, -1.5088,  1.2653],
        [ 0.6495, -1.0408, -0.4185,  0.9769, -1.0902,  0.6305,  2.1492],
        [-0.2247,  0.4983, -0.1879,  0.7205,  0.8975, -0.6949, -1.6695]])

In [17]:
class MyLiner(nn.Module):
    def __init__(self, in_features, out_features, bias=True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weights = nn.Parameter(
        torch.randn(in_features, out_features))
        self.bias = nn.Parameter(torch.randn(out_features))
    def forward(self, x : Tensor):
        return x @ self.weights + self.bias

In [18]:
layer = MyLiner(7,12)


In [20]:
layer(x).shape

torch.Size([5, 12])

In [21]:
for value in layer.parameters():
        print(value)

Parameter containing:
tensor([[-0.8204,  0.3792, -1.0558, -0.3477, -0.5842,  2.3505,  0.3813, -0.3355,
          0.3375, -0.7479,  1.7623,  0.6123],
        [ 0.3561,  0.0386,  0.0182,  1.7331, -0.6285, -1.1544, -0.5772, -1.3066,
         -0.2730,  0.7266,  0.7037, -0.8881],
        [-0.1346,  0.9804,  1.4064, -0.3298,  2.1179, -0.0424, -0.9991,  0.1168,
          1.5361,  0.1111, -0.4965, -1.0457],
        [ 0.1283,  0.1578,  0.6259,  0.2710,  0.3909,  0.5886, -0.6149,  0.1102,
         -0.3286,  0.4757,  1.6702, -0.8112],
        [ 1.7217,  0.2419,  0.4956,  1.9905, -0.5309,  0.8256,  2.3881,  0.9246,
         -0.5995, -0.3279,  0.2247,  1.8743],
        [-2.6881,  0.6147,  0.2739, -0.6337,  0.5644,  1.2869, -0.3849, -0.4787,
         -1.3166, -0.6981,  0.3839, -1.0831],
        [-1.1973, -0.2245,  0.7767,  1.2692,  1.1461, -0.8421,  0.9742, -1.4061,
         -0.6679,  0.9601, -0.4692,  1.3555]], requires_grad=True)
Parameter containing:
tensor([ 2.2477,  0.2390, -0.9327, -1.7559,  0

In [24]:
for epoch in range(epochs):
    # Clear gradient buffers because we don't want any gradient from previous epoch tocarry forward
    optimizer.zero_grad()
    # get output from the model, given the inputs
    outputs = model(inputs)
    # get loss for the predicted output
    loss = criterion(outputs, labels)
    print(loss)
    # get gradients w.r.t to parameters
    loss.backward()
    # update parameters
    optimizer.step()


NameError: name 'epochs' is not defined

In [30]:
from torchvision.datasets import VisionDataset
from typing import Any,Callable, Dict, List, Optional, Tuple
import os

from tqdm import tqdm
import os
import sys
from pathlib import Path
import requests
from skimage import io, transform
import matplotlib.pyplot as plt